" ============================================================================
" Pathogen
" ============================================================================

" Install pathogen:
" cd ~/.vim/bundle
" git clone https://github.com/tpope/vim-pathogen
"
execute pathogen#infect()

" ============================================================================
" Vundle
" ============================================================================

let iCanHazVundle=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle..."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let iCanHazVundle=0
endif
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" ============================================================================
" Vim plugins
" ============================================================================

"Pathogen
Bundle 'tpope/vim-pathogen'
" Vundle
Bundle 'gmarik/vundle'
" Better file browser
Bundle 'scrooloose/nerdtree'
" Code commenter
Bundle 'scrooloose/nerdcommenter'
" Class/module browser
Bundle 'majutsushi/tagbar'
" Code checker
Bundle 'scrooloose/syntastic'
" Code and files fuzzy finder
Bundle 'kien/ctrlp.vim'
" Tab list panel
Bundle 'kien/tabman.vim'
" Diff two directories
Bundle 'will133/vim-dirdiff'
" Powerline
Bundle 'powerline/powerline'
Bundle 'powerline/powerline-fonts'
" Airline
Bundle 'vim-airline/vim-airline'
Bundle 'vim-airline/vim-airline-themes'
" Pending tasks list
Bundle 'fisadev/FixedTaskList.vim'
" Indent text object
Bundle 'michaeljsmith/vim-indent-object'
" Better autocompletion
Bundle 'ycm-core/YouCompleteMe'
" Window chooser
Bundle 't9md/vim-choosewin'
" Git wrapper
Bundle 'tpope/vim-fugitive'
" Git integration
Bundle 'motemen/git-vim'
" Commentary plugin 
Bundle 'tpope/vim-commentary'
" DrawIt plugin 
Bundle 'vim-scripts/drawit'
" Autoformat
Bundle 'Chiel92/vim-autoformat'
" Bash support 
Bundle 'vim-scripts/bash-support.vim'
" C support 
Bundle 'WolfgangMehner/c-support'
" Ctags 
Bundle 'ntnn/vim-ctagser'
" Gutentags
Bundle 'ludovicchabant/vim-gutentags'
"Go To Header plugin 
Bundle 'Yohannfra/Vim-Goto-Header'

" ============================================================================
" Vim settings and mappings
" ============================================================================

filetype off
set nocompatible
set nobackup

" allow plugins by file type
filetype plugin on
filetype indent on

" tabs and spaces handling
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" tab length exceptions on some file types
autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType htmldjango setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2 softtabstop=2

" always show status bar
set ls=2

" incremental search
set incsearch

" highlighted search results
set hlsearch

" syntax highlight on
syntax on

" tab navigation mappings
map tn :tabn<CR>
map tp :tabp<CR>
map tm :tabm 
map tt :tabnew 
map ts :tab split<CR>
map <C-S-Right> :tabn<CR>
imap <C-S-Right> <ESC>:tabn<CR>
map <C-S-Left> :tabp<CR>
imap <C-S-Left> <ESC>:tabp<CR>

" navigate windows with meta+arrows
map <M-Right> <c-w>l
map <M-Left> <c-w>h
map <M-Up> <c-w>k
map <M-Down> <c-w>j
imap <M-Right> <ESC><c-w>l
imap <M-Left> <ESC><c-w>h
imap <M-Up> <ESC><c-w>k
imap <M-Down> <ESC><c-w>j

" enable autocompletion preview window
set completeopt-=preview

" simple recursive grep
command! -nargs=1 RecurGrep lvimgrep /<args>/gj ./**/*.* | lopen | set nowrap
command! -nargs=1 RecurGrepFast silent exec 'lgrep! <q-args> ./**/*.*' | lopen

" mappings to call recursive grep
nmap ,R :RecurGrep 
nmap ,rf :RecurGrepFast 

" mappings to call recursive grep with the default word as search text
nmap ,wR :RecurGrep <cword><CR>
nmap ,wr :RecurGrepFast <cword><CR>

" use 256 colors when possible
if &term =~? 'mlterm\|xterm\|xterm-256\|screen-256'
    let &t_Co = 256
    colorscheme industry 
else
    colorscheme industry 
endif

" when scrolling, keep cursor 3 lines away from screen border
set scrolloff=3

" better backup, swap and undos storage
set directory=~/.vim/dirs/tmp     " directory to place swap files in
set backup                        " make backup files
set backupdir=~/.vim/dirs/backups " where to put backup files
set undofile                      " undo after you re-open the file
set undodir=~/.vim/dirs/undos
set viminfo+=n~/.vim/dirs/viminfo

" create needed directories, if they don't exist
if !isdirectory(&backupdir)
    call mkdir(&backupdir, "p")
endif
if !isdirectory(&directory)
    call mkdir(&directory, "p")
endif
if !isdirectory(&undodir)
    call mkdir(&undodir, "p")
endif

" ============================================================================
" Bundles settings and mappings
" ============================================================================

" Vim leader -----------------------------------------------------------------

let mapleader = ","

" Table mode -----------------------------------------------------------------

let g:table_mode_corner_corner="+"
let g:table_mode_header_fillchar="="

" Tagbar---------------------------------------------------------------------- 

" toggle tagbar display
map <F4> :TagbarToggle<CR>

" autofocus on tagbar open
let g:tagbar_autofocus = 0
"autocmd FileType c call tagbar#autoopen(0)
"autocmd FileType cpp call tagbar#autoopen(0)
"autocmd FileType sh call tagbar#autoopen(0)
"autocmd FileType vim call tagbar#autoopen(0)

" NERDTree ------------------------------------------------------------------- 

" toggle nerdtree display
map <F3> :NERDTreeToggle<CR>

" open nerdtree with the current file selected
nmap ,t :NERDTreeFind<CR>

" Tasklist -------------------------------------------------------------------

" show pending tasks list
map <F2> :TaskList<CR>

" Vim-debug ------------------------------------------------------------------

" disable default mappings, have a lot of conflicts with other plugins
let g:vim_debug_disable_mappings = 1

" add some useful mappings
map <F5> :Dbg over<CR>
map <F6> :Dbg into<CR>
map <F7> :Dbg out<CR>
map <F8> :Dbg here<CR>
map <F9> :Dbg break<CR>
map <F10> :Dbg watch<CR>
map <F11> :Dbg down<CR>
map <F12> :Dbg up<CR>

" Window Chooser -------------------------------------------------------------

" mapping
nmap  -  <Plug>(choosewin)

" show big letters
let g:choosewin_overlay_enable = 1

" Airline --------------------------------------------------------------------

let g:airline_powerline_fonts = 1
let g:airline_theme = 'dark'
let g:airline#extensions#whitespace#enabled = 0
let g:airline#extensions#tabline#buffer_nr_show = 1

" CtrlP ----------------------------------------------------------------------

" file finder mapping
let g:ctrlp_map = ',e'

" tags (symbols) in current file finder mapping
nmap ,g :CtrlPBufTag<CR>

" tags (symbols) in all files finder mapping
nmap ,G :CtrlPBufTagAll<CR>

" general code finder in all files mapping
nmap ,f :CtrlPLine<CR>

" recent files finder mapping
nmap ,m :CtrlPMRUFiles<CR>

" to be able to call CtrlP with default search text
function! CtrlPWithSearchText(search_text, ctrlp_command_end)
    execute ':CtrlP' . a:ctrlp_command_end
    call feedkeys(a:search_text)
endfunction

" same as previous mappings, but calling with current word as default text
nmap ,wg :call CtrlPWithSearchText(expand('<cword>'), 'BufTag')<CR>
nmap ,wG :call CtrlPWithSearchText(expand('<cword>'), 'BufTagAll')<CR>
nmap ,wf :call CtrlPWithSearchText(expand('<cword>'), 'Line')<CR>
nmap ,we :call CtrlPWithSearchText(expand('<cword>'), '')<CR>
nmap ,pe :call CtrlPWithSearchText(expand('<cfile>'), '')<CR>
nmap ,wm :call CtrlPWithSearchText(expand('<cword>'), 'MRUFiles')<CR>
nmap ,wc :call CtrlPWithSearchText(expand('<cword>'), 'CmdPalette')<CR>

" don't change working directory
let g:ctrlp_working_path_mode = 0

" ignore these files and folders on file finder
let g:ctrlp_custom_ignore = {
            \ 'dir':  '\v[\/](\.git|\.hg|\.svn)$',
            \ 'file': '\.pyc$\|\.pyo$',
            \ }

" Syntastic ------------------------------------------------------------------

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_cpp_no_default_include_dirs = 1

" show list of errors and warnings on the current file
nmap <leader>e :Errors<CR>

" check also when just opened the file
let g:syntastic_check_on_open = 1

" don't put icons on the sign column (it hides the vcs status icons of signify)
let g:syntastic_enable_signs = 1

" custom icons (enable them if you use a patched font, and enable the previous 
" setting)
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_style_error_symbol = '✗'
let g:syntastic_style_warning_symbol = '⚠'

" C support -----------------------------------------------------------------

let g:C_UseTool_cmake    = 'yes'
let g:C_UseTool_doxygen  = 'yes'

" C++ manual ----------------------------------------------------------------

command! -nargs=+ Cppman silent! call system("tmux split-window cppman " . expand(<q-args>))
autocmd FileType cpp nnoremap <silent><buffer> K <Esc>:Cppman <cword><CR>

" Autoformat ----------------------------------------------------------------

" formate when saving a file
au BufWrite * :Autoformat

" disable vim's indent file, retabbing and removing trailing whitespace
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0

" NERDCommenter -------------------------------------------------------------

let g:NERDSpaceDelims = 1
let g:NERDTrimTrailingWhitespace = 1

" Gutentags ----------------------------------------------------------------- 

let g:gutentags_add_default_project_roots = 0
let g:gutentags_project_root = ['.git', 'Makefile', 'package.json']
let g:gutentags_generate_on_new = 1
let g:gutentags_generate_on_missing = 1
let g:gutentags_generate_on_write = 1
let g:gutentags_generate_on_empty_buffer = 0
set statusline+=%{gutentags#statusline()}

" YouCompleteMe -------------------------------------------------------------

let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'
let g:ycm_confirm_extra_conf = 1
let g:ycm_add_preview_to_completeopt = -1

" Build key -----------------------------------------------------------------

"nnoremap ,b :!gcc % -o %:r.o <CR>
setlocal makeprg=make\ %:r.o
function Build()
    setlocal bt=nofile bh=wipe nobl noswf ro
    exe 'set bt=nofile bh=wipe nobl noswf ro splitbelow | new | read !gcc --version'
endfunction
nnoremap ,b :call Build() <CR>

